version: '3.8'
services:
  frontend:
    build: .client
    ports:
      - "3000:3000"
  backend:
    build: ./server
    ports:
      - "5000:5000"
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"